# -*- coding: utf-8 -*-
"""khkt_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LyDjF-QmKXvkmdoYqZ7TCm1ve-4TMx58
"""
from os import listdir
from os.path import isfile, join
import os
import csv
import matplotlib.pyplot as plt
rawdataBasePath='dataRaw'
graphBasePath='graph'
wordList = next(os.walk(rawdataBasePath))[1]
for word in wordList:
    wordDataPath=os.path.join(rawdataBasePath,word)
    graphPath=os.path.join(graphBasePath,word)
    # wordDataPath=rawdataBasePath+word
    # graphPath=graphBasePath+word
    if os.path.isdir(graphPath):
        continue
    os.makedirs(graphPath, 0o666) 
    wordFiles = [wordFile for wordFile in listdir(wordDataPath) if isfile(join(wordDataPath, wordFile))]
    for wordFile in wordFiles:
        path=os.path.join(wordDataPath,wordFile)
        print(path)
        file = open(path)
        data = list(csv.reader(file, delimiter=","))[1::]
        image_1 = []
        index_1 = []
        for i in range(0,len(data)):
            image_1.append(int(data[i][2]))
            index_1.append(i)
        fig = plt.figure(figsize=(7,5))
        fig.patch.set_facecolor('white')
        plt.plot(index_1, image_1, label = "brainwave_value")
        plt.axis('off')
        plt.subplots_adjust(left=0.005, bottom=0.005, right=0.995, top=0.995)
        graphName=wordFile.removesuffix('.csv')+'.png'
        plt.savefig(os.path.join(graphPath,graphName))


    # print(wordFiles)



